// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okjkwfspzdccawbnxiqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ramt3ZnNwemRjY2F3Ym54aXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjYzNTYsImV4cCI6MjA3MDQwMjM1Nn0.rG-HtxObRY-1NP_ChGBUsGOYsyjO6dByqLCmlAAd1vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});